# Generated by Django 5.0.6 on 2024-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('job_level', models.CharField(choices=[('entry', 'Entry'), ('jenior', 'Jenior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('job_type', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Any', 'Any')], max_length=10)),
                ('education', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('date_of_job', models.DateField()),
            ],
        ),
    ]
