# Generated by Django 5.0.6 on 2024-05-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Jenior', 'Jenior'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=50),
        ),
    ]
