# Generated by Django 5.0.6 on 2024-05-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('job', '0002_job_company_alter_job_job_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
