# Generated by Django 5.0.6 on 2024-05-23 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_of_job',
        ),
        migrations.AddField(
            model_name='job',
            name='case',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
