# Generated by Django 4.2.5 on 2024-05-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='is_active',
            new_name='is_favorite',
        ),
    ]
