# Generated by Django 4.2.5 on 2024-05-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_is_active_favorite_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
