# Generated by Django 5.0.6 on 2024-05-29 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_favorite_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='age_max',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AddField(
            model_name='job',
            name='age_min',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirements',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
