# Generated by Django 5.0.6 on 2024-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_age_max_job_age_min_job_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=models.CharField(max_length=50),
        ),
    ]
