# Generated by Django 5.0.6 on 2024-07-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='case',
            new_name='active',
        ),
    ]
