# Generated by Django 5.0.6 on 2024-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_case_job_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
