# Generated by Django 5.0.6 on 2024-05-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermanager_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
