# Generated by Django 4.2.5 on 2024-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_edu_level_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=['Male', 'Female'], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_range',
            field=models.IntegerField(max_length=50),
        ),
    ]
