# Generated by Django 5.0.6 on 2024-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employee_bio_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
